---
apiVersion: v1
kind: Pod
metadata:
  name: go-memtest
  namespace: default
  #annotations:
  #  cpu-boost.example.com/cpu-resources: "startup=2.0,runtime=1.0"
  labels:
    app: go-memtest
spec:
  containers:
  - name: go-memtest
    image: us-docker.pkg.dev/gke-demos-345619/gke-demos/go-memtest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 1.0
        memory: 1G
      limits:
        cpu: 1.0
        memory: 1G